services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nestjs-hexagonal-microservice

    ports:
      - '3000:3000'

    env_file:
      - .env

    restart: unless-stopped